import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { Toaster } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Finance Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar />
        <main className="container mx-auto p-4">{children}

        <Toaster position="bottom-right" />

        </main>
      </body>
    </html>
  );
}
